config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :services
  resources :accountables
  resources :accountables
  resources :students
  resources :employees
  resources :classrooms
  resources :grades
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions]
  
  resources :units
  
  as :user do
    match '/users/logout' => 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
    unauthenticated :user do
      root to: 'login#index', as: nil
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  

  root to: "home#index"
  
  get 'enrollments/:id/contract/' => 'enrollments#contract'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    case user.role.to_sym
      when :manager    
        can :manage, :all
      when :secretary
        can :manage, :all
        cannot :manage, Service
      else
        cannot :manage, :all
    end
    
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/accountable.rb
class Accountable < ActiveRecord::Base
	belongs_to :enrollment
	enum gender: [ :male, :female, :not_telling ]
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :teacher, class_name: "Employee"

  before_save :check_teacher

private
  def check_teacher 
    errors[:name] = "You must choose one teacher for classroom." unless self.teacher.role.teacher?
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	extend Enumerize

	enumerize :role, in: [:regular, :teacher, :human_resources, :financier, :coordinator, :manager ], default: :regular

	has_many :classrooms, class_name: "Employee",
                          foreign_key: "teacher_id"
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base

	has_and_belongs_to_many :services
	belongs_to :student
	belongs_to :financial_accountable, :class_name => "Accountable"
	belongs_to :educational_accountable, :class_name => "Accountable"
end

app/models/grade.rb
class Grade < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
	has_and_belongs_to_many :enrollments
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :enrrolments
	enum gender: [ :male, :female ]
end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  extend ActiveModel::Naming
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :password

  enum role: [:regular, :secretary, :teacher, :human_resources, :financier, :coordinator, :manager ]

  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(name: data["name"],
           email: data["email"],
           password: Devise.friendly_token[0,20]
        )
    end
    user
end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
	
	def index
    	authorize! :index, :homepage
  	end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new 
    @unit.sequence = Unit.all.count + 1
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to units_url, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:year, :sequence)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for @unit, :html => { :class => "form-horizontal unit" } do |f| %>

    <% if @unit.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @unit.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :sequence, :class => 'control-label' %>:<%= @unit.sequence %>
    <%= f.hidden_field :sequence %>
  </div>  

  <div class="control-group">
    <%= f.label :year, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :year, (Time.zone.now.year)..(Time.zone.now.year + 5), :class => 'form-control' %>
    </div>
    <%= error_span(@unit[:year]) %>
  </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            units_path, :class => 'btn btn-default' %>

<% end %>

app/views/units/edit.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/units/index.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:sequence) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= link_to unit.id, unit_path(unit) %></td>
        <td><%= unit.year %></td>
        <td><%= unit.sequence %></td>
        <td><%=l unit.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_unit_path(unit), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      unit_path(unit),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_unit_path,
            :class => 'btn btn-primary' %>

app/views/units/new.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/units/show.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= @unit.year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sequence) %>:</strong></dt>
  <dd><%= @unit.sequence %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              units_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_unit_path(@unit), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              unit_path(@unit),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>